name: Select.importOptions
author: chemix
current: 1.2
category: Native
tags: [select]
demo: http://mootools.net/shell/4DmYx/1/
docs: http://github.com/chemix/MooTools.Select.importOptions/blob/master/README.md